update

diff --git a/slackbuild b/slackbuild
--- a/slackbuild
+++ b/slackbuild
@@ -12,8 +12,14 @@ done
 
 osr=`awk </etc/os-release -F= '/VERSION_ID/{print $2}'`
 subdir=`echo $sbo|awk -F\- '{if(NF > 2)print $1}'`
-wget https:/slackbuilds.org/slackbuilds/$osr/
-tar xvf $sbo.tar.gz
+bundle=https:/slackbuilds.org/slackbuilds/$osr/$subdir/$sbo.tar.gz
+if wget $bundle ;then
+	wget $bundle.asc
+	tar xvf $sbo.tar.gz
+else
+	echo "$cmd: Can't find $">&2
+	exit 1
+fi
 sudo chown fulford $sbo 
 cd $sbo 
 . ./$sbo.info
